var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    Object.defineProperty(o, k2, { enumerable: true, get: function() { return m[k]; } });
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __exportStar = (this && this.__exportStar) || function(m, exports) {
    for (var p in m) if (p !== "default" && !Object.prototype.hasOwnProperty.call(exports, p)) __createBinding(exports, m, p);
};
define("Three", ["require", "exports", "./constants.js", "./renderers/WebGLMultisampleRenderTarget.js", "./renderers/WebGLCubeRenderTarget.js", "./renderers/WebGLRenderTarget.js", "./renderers/WebGLRenderer.js", "./renderers/WebGL1Renderer.js", "./renderers/shaders/ShaderLib.js", "./renderers/shaders/UniformsLib.js", "./renderers/shaders/UniformsUtils.js", "./renderers/shaders/ShaderChunk.js", "./scenes/FogExp2.js", "./scenes/Fog.js", "./scenes/Scene.js", "./objects/Sprite.js", "./objects/LOD.js", "./objects/SkinnedMesh.js", "./objects/Skeleton.js", "./objects/Bone.js", "./objects/Mesh.js", "./objects/InstancedMesh.js", "./objects/LineSegments.js", "./objects/LineLoop.js", "./objects/Line.js", "./objects/Points.js", "./objects/Group.js", "./textures/VideoTexture.js", "./textures/DataTexture.js", "./textures/DataTexture2DArray.js", "./textures/DataTexture3D.js", "./textures/CompressedTexture.js", "./textures/CubeTexture.js", "./textures/CanvasTexture.js", "./textures/DepthTexture.js", "./textures/Texture.js", "./geometries/Geometries.js", "./materials/Materials.js", "./loaders/AnimationLoader.js", "./loaders/CompressedTextureLoader.js", "./loaders/CubeTextureLoader.js", "./loaders/DataTextureLoader.js", "./loaders/TextureLoader.js", "./loaders/ObjectLoader.js", "./loaders/MaterialLoader.js", "./loaders/BufferGeometryLoader.js", "./loaders/LoadingManager.js", "./loaders/ImageLoader.js", "./loaders/ImageBitmapLoader.js", "./loaders/FontLoader.js", "./loaders/FileLoader.js", "./loaders/Loader.js", "./loaders/LoaderUtils.js", "./loaders/Cache.js", "./loaders/AudioLoader.js", "./lights/SpotLight.js", "./lights/PointLight.js", "./lights/RectAreaLight.js", "./lights/HemisphereLight.js", "./lights/HemisphereLightProbe.js", "./lights/DirectionalLight.js", "./lights/AmbientLight.js", "./lights/AmbientLightProbe.js", "./lights/Light.js", "./lights/LightProbe.js", "./cameras/StereoCamera.js", "./cameras/PerspectiveCamera.js", "./cameras/OrthographicCamera.js", "./cameras/CubeCamera.js", "./cameras/ArrayCamera.js", "./cameras/Camera.js", "./audio/AudioListener.js", "./audio/PositionalAudio.js", "./audio/AudioContext.js", "./audio/AudioAnalyser.js", "./audio/Audio.js", "./animation/tracks/VectorKeyframeTrack.js", "./animation/tracks/StringKeyframeTrack.js", "./animation/tracks/QuaternionKeyframeTrack.js", "./animation/tracks/NumberKeyframeTrack.js", "./animation/tracks/ColorKeyframeTrack.js", "./animation/tracks/BooleanKeyframeTrack.js", "./animation/PropertyMixer.js", "./animation/PropertyBinding.js", "./animation/KeyframeTrack.js", "./animation/AnimationUtils.js", "./animation/AnimationObjectGroup.js", "./animation/AnimationMixer.js", "./animation/AnimationClip.js", "./core/Uniform.js", "./core/InstancedBufferGeometry.js", "./core/BufferGeometry.js", "./core/Geometry.js", "./core/InterleavedBufferAttribute.js", "./core/InstancedInterleavedBuffer.js", "./core/InterleavedBuffer.js", "./core/InstancedBufferAttribute.js", "./core/GLBufferAttribute.js", "./core/BufferAttribute.js", "./core/Face3.js", "./core/Object3D.js", "./core/Raycaster.js", "./core/Layers.js", "./core/EventDispatcher.js", "./core/Clock.js", "./math/interpolants/QuaternionLinearInterpolant.js", "./math/interpolants/LinearInterpolant.js", "./math/interpolants/DiscreteInterpolant.js", "./math/interpolants/CubicInterpolant.js", "./math/Interpolant.js", "./math/Triangle.js", "./math/MathUtils.js", "./math/Spherical.js", "./math/Cylindrical.js", "./math/Plane.js", "./math/Frustum.js", "./math/Sphere.js", "./math/Ray.js", "./math/Matrix4.js", "./math/Matrix3.js", "./math/Box3.js", "./math/Box2.js", "./math/Line3.js", "./math/Euler.js", "./math/Vector4.js", "./math/Vector3.js", "./math/Vector2.js", "./math/Quaternion.js", "./math/Color.js", "./math/SphericalHarmonics3.js", "./extras/objects/ImmediateRenderObject.js", "./helpers/SpotLightHelper.js", "./helpers/SkeletonHelper.js", "./helpers/PointLightHelper.js", "./helpers/HemisphereLightHelper.js", "./helpers/GridHelper.js", "./helpers/PolarGridHelper.js", "./helpers/DirectionalLightHelper.js", "./helpers/CameraHelper.js", "./helpers/BoxHelper.js", "./helpers/Box3Helper.js", "./helpers/PlaneHelper.js", "./helpers/ArrowHelper.js", "./helpers/AxesHelper.js", "./extras/curves/Curves.js", "./extras/core/Shape.js", "./extras/core/Path.js", "./extras/core/ShapePath.js", "./extras/core/Font.js", "./extras/core/CurvePath.js", "./extras/core/Curve.js", "./extras/DataUtils.js", "./extras/ImageUtils.js", "./extras/ShapeUtils.js", "./extras/PMREMGenerator.js", "./renderers/webgl/WebGLUtils.js", "./constants.js", "./Three.Legacy.js"], function (require, exports, constants_js_1, WebGLMultisampleRenderTarget_js_1, WebGLCubeRenderTarget_js_1, WebGLRenderTarget_js_1, WebGLRenderer_js_1, WebGL1Renderer_js_1, ShaderLib_js_1, UniformsLib_js_1, UniformsUtils_js_1, ShaderChunk_js_1, FogExp2_js_1, Fog_js_1, Scene_js_1, Sprite_js_1, LOD_js_1, SkinnedMesh_js_1, Skeleton_js_1, Bone_js_1, Mesh_js_1, InstancedMesh_js_1, LineSegments_js_1, LineLoop_js_1, Line_js_1, Points_js_1, Group_js_1, VideoTexture_js_1, DataTexture_js_1, DataTexture2DArray_js_1, DataTexture3D_js_1, CompressedTexture_js_1, CubeTexture_js_1, CanvasTexture_js_1, DepthTexture_js_1, Texture_js_1, Geometries_js_1, Materials_js_1, AnimationLoader_js_1, CompressedTextureLoader_js_1, CubeTextureLoader_js_1, DataTextureLoader_js_1, TextureLoader_js_1, ObjectLoader_js_1, MaterialLoader_js_1, BufferGeometryLoader_js_1, LoadingManager_js_1, ImageLoader_js_1, ImageBitmapLoader_js_1, FontLoader_js_1, FileLoader_js_1, Loader_js_1, LoaderUtils_js_1, Cache_js_1, AudioLoader_js_1, SpotLight_js_1, PointLight_js_1, RectAreaLight_js_1, HemisphereLight_js_1, HemisphereLightProbe_js_1, DirectionalLight_js_1, AmbientLight_js_1, AmbientLightProbe_js_1, Light_js_1, LightProbe_js_1, StereoCamera_js_1, PerspectiveCamera_js_1, OrthographicCamera_js_1, CubeCamera_js_1, ArrayCamera_js_1, Camera_js_1, AudioListener_js_1, PositionalAudio_js_1, AudioContext_js_1, AudioAnalyser_js_1, Audio_js_1, VectorKeyframeTrack_js_1, StringKeyframeTrack_js_1, QuaternionKeyframeTrack_js_1, NumberKeyframeTrack_js_1, ColorKeyframeTrack_js_1, BooleanKeyframeTrack_js_1, PropertyMixer_js_1, PropertyBinding_js_1, KeyframeTrack_js_1, AnimationUtils_js_1, AnimationObjectGroup_js_1, AnimationMixer_js_1, AnimationClip_js_1, Uniform_js_1, InstancedBufferGeometry_js_1, BufferGeometry_js_1, Geometry_js_1, InterleavedBufferAttribute_js_1, InstancedInterleavedBuffer_js_1, InterleavedBuffer_js_1, InstancedBufferAttribute_js_1, GLBufferAttribute_js_1, BufferAttribute_js_1, Face3_js_1, Object3D_js_1, Raycaster_js_1, Layers_js_1, EventDispatcher_js_1, Clock_js_1, QuaternionLinearInterpolant_js_1, LinearInterpolant_js_1, DiscreteInterpolant_js_1, CubicInterpolant_js_1, Interpolant_js_1, Triangle_js_1, MathUtils_js_1, Spherical_js_1, Cylindrical_js_1, Plane_js_1, Frustum_js_1, Sphere_js_1, Ray_js_1, Matrix4_js_1, Matrix3_js_1, Box3_js_1, Box2_js_1, Line3_js_1, Euler_js_1, Vector4_js_1, Vector3_js_1, Vector2_js_1, Quaternion_js_1, Color_js_1, SphericalHarmonics3_js_1, ImmediateRenderObject_js_1, SpotLightHelper_js_1, SkeletonHelper_js_1, PointLightHelper_js_1, HemisphereLightHelper_js_1, GridHelper_js_1, PolarGridHelper_js_1, DirectionalLightHelper_js_1, CameraHelper_js_1, BoxHelper_js_1, Box3Helper_js_1, PlaneHelper_js_1, ArrowHelper_js_1, AxesHelper_js_1, Curves_js_1, Shape_js_1, Path_js_1, ShapePath_js_1, Font_js_1, CurvePath_js_1, Curve_js_1, DataUtils_js_1, ImageUtils_js_1, ShapeUtils_js_1, PMREMGenerator_js_1, WebGLUtils_js_1, constants_js_2, Three_Legacy_js_1) {
    "use strict";
    exports.__esModule = true;
    exports.WebGLUtils = exports.PMREMGenerator = exports.ShapeUtils = exports.ImageUtils = exports.DataUtils = exports.Curve = exports.CurvePath = exports.Font = exports.ShapePath = exports.Path = exports.Shape = exports.AxesHelper = exports.ArrowHelper = exports.PlaneHelper = exports.Box3Helper = exports.BoxHelper = exports.CameraHelper = exports.DirectionalLightHelper = exports.PolarGridHelper = exports.GridHelper = exports.HemisphereLightHelper = exports.PointLightHelper = exports.SkeletonHelper = exports.SpotLightHelper = exports.ImmediateRenderObject = exports.SphericalHarmonics3 = exports.Color = exports.Quaternion = exports.Vector2 = exports.Vector3 = exports.Vector4 = exports.Euler = exports.Line3 = exports.Box2 = exports.Box3 = exports.Matrix3 = exports.Matrix4 = exports.Ray = exports.Sphere = exports.Frustum = exports.Plane = exports.Cylindrical = exports.Spherical = exports.MathUtils = exports.Triangle = exports.Interpolant = exports.CubicInterpolant = exports.DiscreteInterpolant = exports.LinearInterpolant = exports.QuaternionLinearInterpolant = exports.Clock = exports.EventDispatcher = exports.Layers = exports.Raycaster = exports.Object3D = exports.Face3 = exports.GLBufferAttribute = exports.InstancedBufferAttribute = exports.InterleavedBuffer = exports.InstancedInterleavedBuffer = exports.InterleavedBufferAttribute = exports.Geometry = exports.BufferGeometry = exports.InstancedBufferGeometry = exports.Uniform = exports.AnimationClip = exports.AnimationMixer = exports.AnimationObjectGroup = exports.AnimationUtils = exports.KeyframeTrack = exports.PropertyBinding = exports.PropertyMixer = exports.BooleanKeyframeTrack = exports.ColorKeyframeTrack = exports.NumberKeyframeTrack = exports.QuaternionKeyframeTrack = exports.StringKeyframeTrack = exports.VectorKeyframeTrack = exports.Audio = exports.AudioAnalyser = exports.AudioContext = exports.PositionalAudio = exports.AudioListener = exports.Camera = exports.ArrayCamera = exports.CubeCamera = exports.OrthographicCamera = exports.PerspectiveCamera = exports.StereoCamera = exports.LightProbe = exports.Light = exports.AmbientLightProbe = exports.AmbientLight = exports.DirectionalLight = exports.HemisphereLightProbe = exports.HemisphereLight = exports.RectAreaLight = exports.PointLight = exports.SpotLight = exports.AudioLoader = exports.Cache = exports.LoaderUtils = exports.Loader = exports.FileLoader = exports.FontLoader = exports.ImageBitmapLoader = exports.ImageLoader = exports.LoadingManager = exports.DefaultLoadingManager = exports.BufferGeometryLoader = exports.MaterialLoader = exports.ObjectLoader = exports.TextureLoader = exports.DataTextureLoader = exports.CubeTextureLoader = exports.CompressedTextureLoader = exports.AnimationLoader = exports.Texture = exports.DepthTexture = exports.CanvasTexture = exports.CubeTexture = exports.CompressedTexture = exports.DataTexture3D = exports.DataTexture2DArray = exports.DataTexture = exports.VideoTexture = exports.Group = exports.Points = exports.Line = exports.LineLoop = exports.LineSegments = exports.InstancedMesh = exports.Mesh = exports.Bone = exports.Skeleton = exports.SkinnedMesh = exports.LOD = exports.Sprite = exports.Scene = exports.Fog = exports.FogExp2 = exports.ShaderChunk = exports.UniformsUtils = exports.UniformsLib = exports.ShaderLib = exports.WebGL1Renderer = exports.WebGLRenderer = exports.WebGLRenderTarget = exports.WebGLCubeRenderTarget = exports.WebGLMultisampleRenderTarget = void 0;
    __createBinding(exports, WebGLMultisampleRenderTarget_js_1, "WebGLMultisampleRenderTarget");
    __createBinding(exports, WebGLCubeRenderTarget_js_1, "WebGLCubeRenderTarget");
    __createBinding(exports, WebGLRenderTarget_js_1, "WebGLRenderTarget");
    __createBinding(exports, WebGLRenderer_js_1, "WebGLRenderer");
    __createBinding(exports, WebGL1Renderer_js_1, "WebGL1Renderer");
    __createBinding(exports, ShaderLib_js_1, "ShaderLib");
    __createBinding(exports, UniformsLib_js_1, "UniformsLib");
    __createBinding(exports, UniformsUtils_js_1, "UniformsUtils");
    __createBinding(exports, ShaderChunk_js_1, "ShaderChunk");
    __createBinding(exports, FogExp2_js_1, "FogExp2");
    __createBinding(exports, Fog_js_1, "Fog");
    __createBinding(exports, Scene_js_1, "Scene");
    __createBinding(exports, Sprite_js_1, "Sprite");
    __createBinding(exports, LOD_js_1, "LOD");
    __createBinding(exports, SkinnedMesh_js_1, "SkinnedMesh");
    __createBinding(exports, Skeleton_js_1, "Skeleton");
    __createBinding(exports, Bone_js_1, "Bone");
    __createBinding(exports, Mesh_js_1, "Mesh");
    __createBinding(exports, InstancedMesh_js_1, "InstancedMesh");
    __createBinding(exports, LineSegments_js_1, "LineSegments");
    __createBinding(exports, LineLoop_js_1, "LineLoop");
    __createBinding(exports, Line_js_1, "Line");
    __createBinding(exports, Points_js_1, "Points");
    __createBinding(exports, Group_js_1, "Group");
    __createBinding(exports, VideoTexture_js_1, "VideoTexture");
    __createBinding(exports, DataTexture_js_1, "DataTexture");
    __createBinding(exports, DataTexture2DArray_js_1, "DataTexture2DArray");
    __createBinding(exports, DataTexture3D_js_1, "DataTexture3D");
    __createBinding(exports, CompressedTexture_js_1, "CompressedTexture");
    __createBinding(exports, CubeTexture_js_1, "CubeTexture");
    __createBinding(exports, CanvasTexture_js_1, "CanvasTexture");
    __createBinding(exports, DepthTexture_js_1, "DepthTexture");
    __createBinding(exports, Texture_js_1, "Texture");
    __exportStar(Geometries_js_1, exports);
    __exportStar(Materials_js_1, exports);
    __createBinding(exports, AnimationLoader_js_1, "AnimationLoader");
    __createBinding(exports, CompressedTextureLoader_js_1, "CompressedTextureLoader");
    __createBinding(exports, CubeTextureLoader_js_1, "CubeTextureLoader");
    __createBinding(exports, DataTextureLoader_js_1, "DataTextureLoader");
    __createBinding(exports, TextureLoader_js_1, "TextureLoader");
    __createBinding(exports, ObjectLoader_js_1, "ObjectLoader");
    __createBinding(exports, MaterialLoader_js_1, "MaterialLoader");
    __createBinding(exports, BufferGeometryLoader_js_1, "BufferGeometryLoader");
    __createBinding(exports, LoadingManager_js_1, "DefaultLoadingManager");
    __createBinding(exports, LoadingManager_js_1, "LoadingManager");
    __createBinding(exports, ImageLoader_js_1, "ImageLoader");
    __createBinding(exports, ImageBitmapLoader_js_1, "ImageBitmapLoader");
    __createBinding(exports, FontLoader_js_1, "FontLoader");
    __createBinding(exports, FileLoader_js_1, "FileLoader");
    __createBinding(exports, Loader_js_1, "Loader");
    __createBinding(exports, LoaderUtils_js_1, "LoaderUtils");
    __createBinding(exports, Cache_js_1, "Cache");
    __createBinding(exports, AudioLoader_js_1, "AudioLoader");
    __createBinding(exports, SpotLight_js_1, "SpotLight");
    __createBinding(exports, PointLight_js_1, "PointLight");
    __createBinding(exports, RectAreaLight_js_1, "RectAreaLight");
    __createBinding(exports, HemisphereLight_js_1, "HemisphereLight");
    __createBinding(exports, HemisphereLightProbe_js_1, "HemisphereLightProbe");
    __createBinding(exports, DirectionalLight_js_1, "DirectionalLight");
    __createBinding(exports, AmbientLight_js_1, "AmbientLight");
    __createBinding(exports, AmbientLightProbe_js_1, "AmbientLightProbe");
    __createBinding(exports, Light_js_1, "Light");
    __createBinding(exports, LightProbe_js_1, "LightProbe");
    __createBinding(exports, StereoCamera_js_1, "StereoCamera");
    __createBinding(exports, PerspectiveCamera_js_1, "PerspectiveCamera");
    __createBinding(exports, OrthographicCamera_js_1, "OrthographicCamera");
    __createBinding(exports, CubeCamera_js_1, "CubeCamera");
    __createBinding(exports, ArrayCamera_js_1, "ArrayCamera");
    __createBinding(exports, Camera_js_1, "Camera");
    __createBinding(exports, AudioListener_js_1, "AudioListener");
    __createBinding(exports, PositionalAudio_js_1, "PositionalAudio");
    __createBinding(exports, AudioContext_js_1, "AudioContext");
    __createBinding(exports, AudioAnalyser_js_1, "AudioAnalyser");
    __createBinding(exports, Audio_js_1, "Audio");
    __createBinding(exports, VectorKeyframeTrack_js_1, "VectorKeyframeTrack");
    __createBinding(exports, StringKeyframeTrack_js_1, "StringKeyframeTrack");
    __createBinding(exports, QuaternionKeyframeTrack_js_1, "QuaternionKeyframeTrack");
    __createBinding(exports, NumberKeyframeTrack_js_1, "NumberKeyframeTrack");
    __createBinding(exports, ColorKeyframeTrack_js_1, "ColorKeyframeTrack");
    __createBinding(exports, BooleanKeyframeTrack_js_1, "BooleanKeyframeTrack");
    __createBinding(exports, PropertyMixer_js_1, "PropertyMixer");
    __createBinding(exports, PropertyBinding_js_1, "PropertyBinding");
    __createBinding(exports, KeyframeTrack_js_1, "KeyframeTrack");
    __createBinding(exports, AnimationUtils_js_1, "AnimationUtils");
    __createBinding(exports, AnimationObjectGroup_js_1, "AnimationObjectGroup");
    __createBinding(exports, AnimationMixer_js_1, "AnimationMixer");
    __createBinding(exports, AnimationClip_js_1, "AnimationClip");
    __createBinding(exports, Uniform_js_1, "Uniform");
    __createBinding(exports, InstancedBufferGeometry_js_1, "InstancedBufferGeometry");
    __createBinding(exports, BufferGeometry_js_1, "BufferGeometry");
    __createBinding(exports, Geometry_js_1, "Geometry");
    __createBinding(exports, InterleavedBufferAttribute_js_1, "InterleavedBufferAttribute");
    __createBinding(exports, InstancedInterleavedBuffer_js_1, "InstancedInterleavedBuffer");
    __createBinding(exports, InterleavedBuffer_js_1, "InterleavedBuffer");
    __createBinding(exports, InstancedBufferAttribute_js_1, "InstancedBufferAttribute");
    __createBinding(exports, GLBufferAttribute_js_1, "GLBufferAttribute");
    __exportStar(BufferAttribute_js_1, exports);
    __createBinding(exports, Face3_js_1, "Face3");
    __createBinding(exports, Object3D_js_1, "Object3D");
    __createBinding(exports, Raycaster_js_1, "Raycaster");
    __createBinding(exports, Layers_js_1, "Layers");
    __createBinding(exports, EventDispatcher_js_1, "EventDispatcher");
    __createBinding(exports, Clock_js_1, "Clock");
    __createBinding(exports, QuaternionLinearInterpolant_js_1, "QuaternionLinearInterpolant");
    __createBinding(exports, LinearInterpolant_js_1, "LinearInterpolant");
    __createBinding(exports, DiscreteInterpolant_js_1, "DiscreteInterpolant");
    __createBinding(exports, CubicInterpolant_js_1, "CubicInterpolant");
    __createBinding(exports, Interpolant_js_1, "Interpolant");
    __createBinding(exports, Triangle_js_1, "Triangle");
    __createBinding(exports, MathUtils_js_1, "MathUtils");
    __createBinding(exports, Spherical_js_1, "Spherical");
    __createBinding(exports, Cylindrical_js_1, "Cylindrical");
    __createBinding(exports, Plane_js_1, "Plane");
    __createBinding(exports, Frustum_js_1, "Frustum");
    __createBinding(exports, Sphere_js_1, "Sphere");
    __createBinding(exports, Ray_js_1, "Ray");
    __createBinding(exports, Matrix4_js_1, "Matrix4");
    __createBinding(exports, Matrix3_js_1, "Matrix3");
    __createBinding(exports, Box3_js_1, "Box3");
    __createBinding(exports, Box2_js_1, "Box2");
    __createBinding(exports, Line3_js_1, "Line3");
    __createBinding(exports, Euler_js_1, "Euler");
    __createBinding(exports, Vector4_js_1, "Vector4");
    __createBinding(exports, Vector3_js_1, "Vector3");
    __createBinding(exports, Vector2_js_1, "Vector2");
    __createBinding(exports, Quaternion_js_1, "Quaternion");
    __createBinding(exports, Color_js_1, "Color");
    __createBinding(exports, SphericalHarmonics3_js_1, "SphericalHarmonics3");
    __createBinding(exports, ImmediateRenderObject_js_1, "ImmediateRenderObject");
    __createBinding(exports, SpotLightHelper_js_1, "SpotLightHelper");
    __createBinding(exports, SkeletonHelper_js_1, "SkeletonHelper");
    __createBinding(exports, PointLightHelper_js_1, "PointLightHelper");
    __createBinding(exports, HemisphereLightHelper_js_1, "HemisphereLightHelper");
    __createBinding(exports, GridHelper_js_1, "GridHelper");
    __createBinding(exports, PolarGridHelper_js_1, "PolarGridHelper");
    __createBinding(exports, DirectionalLightHelper_js_1, "DirectionalLightHelper");
    __createBinding(exports, CameraHelper_js_1, "CameraHelper");
    __createBinding(exports, BoxHelper_js_1, "BoxHelper");
    __createBinding(exports, Box3Helper_js_1, "Box3Helper");
    __createBinding(exports, PlaneHelper_js_1, "PlaneHelper");
    __createBinding(exports, ArrowHelper_js_1, "ArrowHelper");
    __createBinding(exports, AxesHelper_js_1, "AxesHelper");
    __exportStar(Curves_js_1, exports);
    __createBinding(exports, Shape_js_1, "Shape");
    __createBinding(exports, Path_js_1, "Path");
    __createBinding(exports, ShapePath_js_1, "ShapePath");
    __createBinding(exports, Font_js_1, "Font");
    __createBinding(exports, CurvePath_js_1, "CurvePath");
    __createBinding(exports, Curve_js_1, "Curve");
    __createBinding(exports, DataUtils_js_1, "DataUtils");
    __createBinding(exports, ImageUtils_js_1, "ImageUtils");
    __createBinding(exports, ShapeUtils_js_1, "ShapeUtils");
    __createBinding(exports, PMREMGenerator_js_1, "PMREMGenerator");
    __createBinding(exports, WebGLUtils_js_1, "WebGLUtils");
    __exportStar(constants_js_2, exports);
    __exportStar(Three_Legacy_js_1, exports);
    if (typeof __THREE_DEVTOOLS__ !== 'undefined') {
        /* eslint-disable no-undef */
        __THREE_DEVTOOLS__.dispatchEvent(new CustomEvent('register', { detail: {
                revision: constants_js_1.REVISION
            } }));
        /* eslint-enable no-undef */
    }
});
